NCS_ITEMS = [
    # 경영·회계·사무
    {
        "ncs_code": "02010101",
        "large_cat": "경영·회계·사무",
        "middle_cat": "기획사무",
        "small_cat": "경영기획",
        "unit_name": "경영계획 수립",
        "unit_desc": "조직의 비전·목표를 달성하기 위해 내외부 환경을 분석하고 전략적 경영계획을 수립하는 역량",
    },
    {
        "ncs_code": "02010201",
        "large_cat": "경영·회계·사무",
        "middle_cat": "기획사무",
        "small_cat": "PR·홍보",
        "unit_name": "홍보 콘텐츠 제작",
        "unit_desc": "브랜드 가치를 높이기 위해 SNS·영상·텍스트 등 다양한 매체용 홍보 콘텐츠를 기획·제작하는 역량",
    },
    {
        "ncs_code": "02020101",
        "large_cat": "경영·회계·사무",
        "middle_cat": "총무·인사",
        "small_cat": "인사",
        "unit_name": "채용 관리",
        "unit_desc": "조직에 필요한 인재를 선발하기 위해 채용 계획을 수립하고 전형을 운영하는 역량",
    },
    {
        "ncs_code": "02020201",
        "large_cat": "경영·회계·사무",
        "middle_cat": "총무·인사",
        "small_cat": "총무",
        "unit_name": "문서 작성 및 관리",
        "unit_desc": "업무 목적에 맞는 보고서·기획서·공문 등을 작성하고 체계적으로 관리하는 역량",
    },
    {
        "ncs_code": "02030101",
        "large_cat": "경영·회계·사무",
        "middle_cat": "재무·회계",
        "small_cat": "회계",
        "unit_name": "회계 정보 처리",
        "unit_desc": "거래 발생에 따른 분개·전기·결산 등 회계 정보를 정확하게 기록·관리하는 역량",
    },
    # 정보통신
    {
        "ncs_code": "20010101",
        "large_cat": "정보통신",
        "middle_cat": "정보기술",
        "small_cat": "소프트웨어개발",
        "unit_name": "프로그래밍 언어 활용",
        "unit_desc": "요구사항 분석을 바탕으로 적절한 프로그래밍 언어를 선택하여 소프트웨어를 개발하는 역량",
    },
    {
        "ncs_code": "20010201",
        "large_cat": "정보통신",
        "middle_cat": "정보기술",
        "small_cat": "소프트웨어개발",
        "unit_name": "데이터베이스 구축",
        "unit_desc": "효율적인 데이터 관리를 위해 DB를 설계·구축하고 SQL로 데이터를 조작하는 역량",
    },
    {
        "ncs_code": "20010301",
        "large_cat": "정보통신",
        "middle_cat": "정보기술",
        "small_cat": "UI/UX",
        "unit_name": "UI/UX 기획",
        "unit_desc": "사용자 조사를 기반으로 직관적이고 편리한 인터페이스를 설계·프로토타이핑하는 역량",
    },
    {
        "ncs_code": "20020101",
        "large_cat": "정보통신",
        "middle_cat": "정보기술",
        "small_cat": "데이터분석",
        "unit_name": "데이터 수집·분석",
        "unit_desc": "다양한 출처의 데이터를 수집·정제하고 통계·시각화 도구로 인사이트를 도출하는 역량",
    },
    {
        "ncs_code": "20020201",
        "large_cat": "정보통신",
        "middle_cat": "정보기술",
        "small_cat": "데이터분석",
        "unit_name": "머신러닝 모델 개발",
        "unit_desc": "데이터 기반으로 예측·분류·군집 등 머신러닝 모델을 설계·학습·평가하는 역량",
    },
    # 금융·보험
    {
        "ncs_code": "03010101",
        "large_cat": "금융·보험",
        "middle_cat": "금융",
        "small_cat": "자산관리",
        "unit_name": "금융 상품 분석",
        "unit_desc": "고객 재무 목표에 맞는 금융 상품을 비교·분석하여 최적의 포트폴리오를 제안하는 역량",
    },
    {
        "ncs_code": "03020101",
        "large_cat": "금융·보험",
        "middle_cat": "보험",
        "small_cat": "보험영업",
        "unit_name": "고객 니즈 파악 및 상담",
        "unit_desc": "고객의 위험 상황과 니즈를 분석하여 적합한 보험 상품을 제안·설명하는 역량",
    },
    # 판매·영업
    {
        "ncs_code": "41010101",
        "large_cat": "판매영업",
        "middle_cat": "영업",
        "small_cat": "고객관리",
        "unit_name": "고객 상담 및 관계 관리",
        "unit_desc": "고객의 요구사항을 파악하여 맞춤형 서비스를 제공하고 장기적 신뢰 관계를 구축하는 역량",
    },
    {
        "ncs_code": "41010201",
        "large_cat": "판매영업",
        "middle_cat": "영업",
        "small_cat": "마케팅",
        "unit_name": "시장 조사 및 마케팅 전략 수립",
        "unit_desc": "시장 트렌드와 경쟁사를 분석하고 타겟 고객 중심의 마케팅 전략을 수립하는 역량",
    },
    {
        "ncs_code": "41020101",
        "large_cat": "판매영업",
        "middle_cat": "유통",
        "small_cat": "물류관리",
        "unit_name": "재고 및 물류 관리",
        "unit_desc": "최적의 재고 수준을 유지하고 입출고 흐름을 관리하여 공급망 효율성을 높이는 역량",
    },
    # 교육
    {
        "ncs_code": "05010101",
        "large_cat": "교육·자연·사회과학",
        "middle_cat": "교육",
        "small_cat": "학습지도",
        "unit_name": "교육 프로그램 설계",
        "unit_desc": "학습자의 수준과 목표를 고려하여 체계적인 교육과정과 콘텐츠를 설계하는 역량",
    },
    {
        "ncs_code": "05010201",
        "large_cat": "교육·자연·사회과학",
        "middle_cat": "교육",
        "small_cat": "교육행정",
        "unit_name": "교육 행정 지원",
        "unit_desc": "교육 기관 운영에 필요한 행정 업무를 수행하고 교육 환경을 체계적으로 관리하는 역량",
    },
    # 사회복지
    {
        "ncs_code": "07010101",
        "large_cat": "사회복지·종교",
        "middle_cat": "사회복지",
        "small_cat": "사회복지서비스",
        "unit_name": "복지 대상자 상담",
        "unit_desc": "복지 대상자의 상황을 파악하고 필요한 서비스를 연계·지원하는 역량",
    },
    {
        "ncs_code": "07010201",
        "large_cat": "사회복지·종교",
        "middle_cat": "사회복지",
        "small_cat": "자원봉사관리",
        "unit_name": "자원봉사 프로그램 운영",
        "unit_desc": "자원봉사자를 모집·교육·배치하고 봉사 프로그램을 기획·운영하는 역량",
    },
    # 문화·예술
    {
        "ncs_code": "09010101",
        "large_cat": "문화·예술·디자인·방송",
        "middle_cat": "디자인",
        "small_cat": "시각디자인",
        "unit_name": "시각 콘텐츠 디자인",
        "unit_desc": "브랜드 아이덴티티에 맞는 인쇄물·디지털 그래픽·영상 등 시각 콘텐츠를 제작하는 역량",
    },
    {
        "ncs_code": "09020101",
        "large_cat": "문화·예술·디자인·방송",
        "middle_cat": "방송",
        "small_cat": "영상콘텐츠",
        "unit_name": "영상 기획·제작",
        "unit_desc": "기획 의도에 맞는 영상 스토리보드를 작성하고 촬영·편집하여 완성된 콘텐츠를 제작하는 역량",
    },
    # 보건·의료
    {
        "ncs_code": "06010101",
        "large_cat": "보건·의료",
        "middle_cat": "의료",
        "small_cat": "의료지원",
        "unit_name": "의료 행정 관리",
        "unit_desc": "원무·진료 예약·의무기록 등 의료기관 행정 업무를 처리하는 역량",
    },
    # 음식서비스
    {
        "ncs_code": "13010101",
        "large_cat": "음식서비스",
        "middle_cat": "조리",
        "small_cat": "한식조리",
        "unit_name": "식재료 관리 및 위생 처리",
        "unit_desc": "식재료를 안전하게 보관·전처리하고 위생 기준에 따라 조리 환경을 관리하는 역량",
    },
    # 건설
    {
        "ncs_code": "11010101",
        "large_cat": "건설",
        "middle_cat": "건축",
        "small_cat": "건축설계",
        "unit_name": "건축 설계 도면 작성",
        "unit_desc": "건축물의 구조·용도를 고려하여 CAD 등을 활용해 정확한 설계 도면을 작성하는 역량",
    },
    # 환경·에너지
    {
        "ncs_code": "18010101",
        "large_cat": "환경·에너지·안전",
        "middle_cat": "환경",
        "small_cat": "환경관리",
        "unit_name": "환경 영향 평가",
        "unit_desc": "개발 사업이 환경에 미치는 영향을 조사·분석하여 저감 방안을 수립하는 역량",
    },
    # 공통 역량
    {
        "ncs_code": "99010101",
        "large_cat": "공통",
        "middle_cat": "직업기초능력",
        "small_cat": "의사소통",
        "unit_name": "의사소통 능력",
        "unit_desc": "상대방의 의도를 정확히 파악하고 자신의 생각을 명확하게 전달하는 역량",
    },
    {
        "ncs_code": "99010201",
        "large_cat": "공통",
        "middle_cat": "직업기초능력",
        "small_cat": "문제해결",
        "unit_name": "문제해결 능력",
        "unit_desc": "업무 중 발생하는 문제를 논리적으로 분석하고 창의적인 해결 방안을 도출하는 역량",
    },
    {
        "ncs_code": "99010301",
        "large_cat": "공통",
        "middle_cat": "직업기초능력",
        "small_cat": "자기개발",
        "unit_name": "자기개발 능력",
        "unit_desc": "직업인으로 성장하기 위해 스스로 학습 목표를 설정하고 지속적으로 역량을 개발하는 역량",
    },
    {
        "ncs_code": "99010401",
        "large_cat": "공통",
        "middle_cat": "직업기초능력",
        "small_cat": "대인관계",
        "unit_name": "팀워크 및 협업",
        "unit_desc": "다양한 구성원과 협력하여 공동 목표를 달성하고 갈등을 조율하는 역량",
    },
    {
        "ncs_code": "99010501",
        "large_cat": "공통",
        "middle_cat": "직업기초능력",
        "small_cat": "정보능력",
        "unit_name": "정보 수집·활용 능력",
        "unit_desc": "업무에 필요한 정보를 다양한 경로로 수집하고 분석·가공하여 의사결정에 활용하는 역량",
    },
    {
        "ncs_code": "99010601",
        "large_cat": "공통",
        "middle_cat": "직업기초능력",
        "small_cat": "조직이해",
        "unit_name": "조직 이해 및 적응",
        "unit_desc": "조직의 문화·구조·목표를 이해하고 맡은 역할에 맞게 업무를 수행하는 역량",
    },
]
