"""Seed senior persona sample data. Run once or rerun safely."""
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from database import SessionLocal, Base, engine
from models import SeniorPersona


SENIOR_PERSONAS = [
    # ── 데이터 분석 계열 ─────────────────────────────────────────────
    {
        "user_id": "senior_kim_a",
        "user_name": "김민준",
        "avatar_label": "김민",
        "avatar_color": "#f0ede7",
        "department": "경영학",
        "gap_period": "5개월",
        "certifications": "ADsP, SQLD",
        "employment_field": "데이터 분석",
        "employment_company_type": "중견기업",
        "career_path_summary": "경영학 → 데이터 분석 취업",
        "similarity_score": 94.0,
        "is_accepted": True,
        "match_note": "경영 지식 + 데이터 자격증 조합으로 빠른 전환",
    },
    {
        "user_id": "senior_lee_b",
        "user_name": "이서연",
        "avatar_label": "이서",
        "avatar_color": "#e8f0f7",
        "department": "통계학",
        "gap_period": "4개월",
        "certifications": "빅데이터분석기사, ADsP",
        "employment_field": "데이터 분석",
        "employment_company_type": "대기업",
        "career_path_summary": "통계학 → 대기업 데이터 분석",
        "similarity_score": 91.0,
        "is_accepted": True,
        "match_note": "전공 강점을 자격증으로 증명한 사례",
    },
    {
        "user_id": "senior_park_c",
        "user_name": "박지훈",
        "avatar_label": "박지",
        "avatar_color": "#f0f7ee",
        "department": "문과",
        "gap_period": "7개월",
        "certifications": "ADsP, 컴퓨터활용능력 1급",
        "employment_field": "데이터 분석",
        "employment_company_type": "스타트업",
        "career_path_summary": "문과 → 데이터 분석 스타트업 취업",
        "similarity_score": 85.0,
        "is_accepted": True,
        "match_note": "문과 출신 데이터 직무 전환 대표 사례",
    },
    {
        "user_id": "senior_choi_d",
        "user_name": "최수아",
        "avatar_label": "최수",
        "avatar_color": "#fff2dd",
        "department": "수학",
        "gap_period": "3개월",
        "certifications": "빅데이터분석기사, SQLD",
        "employment_field": "데이터 엔지니어링",
        "employment_company_type": "IT서비스",
        "career_path_summary": "수학 → 데이터 엔지니어링",
        "similarity_score": 88.0,
        "is_accepted": True,
        "match_note": "수학 전공 강점으로 최단기 취업",
    },

    # ── AI / 머신러닝 계열 ───────────────────────────────────────────
    {
        "user_id": "senior_jung_e",
        "user_name": "정도현",
        "avatar_label": "정도",
        "avatar_color": "#edf3ff",
        "department": "컴퓨터공학",
        "gap_period": "3개월",
        "certifications": "정보처리기사, ADsP",
        "employment_field": "AI 모델링",
        "employment_company_type": "AI 스타트업",
        "career_path_summary": "컴퓨터공학 → AI 스타트업",
        "similarity_score": 90.0,
        "is_accepted": True,
        "match_note": "프로젝트 포트폴리오 중심으로 빠른 취업",
    },
    {
        "user_id": "senior_han_f",
        "user_name": "한예린",
        "avatar_label": "한예",
        "avatar_color": "#f7edf5",
        "department": "통계학",
        "gap_period": "6개월",
        "certifications": "빅데이터분석기사, ADsP",
        "employment_field": "AI 모델링",
        "employment_company_type": "대기업",
        "career_path_summary": "통계학 → 대기업 AI팀",
        "similarity_score": 86.0,
        "is_accepted": True,
        "match_note": "통계 + 머신러닝 프로젝트 결합 사례",
    },

    # ── 백엔드 / 개발 계열 ───────────────────────────────────────────
    {
        "user_id": "senior_oh_g",
        "user_name": "오태양",
        "avatar_label": "오태",
        "avatar_color": "#eaf7f2",
        "department": "비전공자",
        "gap_period": "8개월",
        "certifications": "정보처리기사, SQLD",
        "employment_field": "백엔드 개발",
        "employment_company_type": "SI기업",
        "career_path_summary": "비전공 독학 → SI기업 백엔드",
        "similarity_score": 82.0,
        "is_accepted": True,
        "match_note": "비전공 출신 개발 직무 전환 성공 사례",
    },
    {
        "user_id": "senior_yoon_h",
        "user_name": "윤재원",
        "avatar_label": "윤재",
        "avatar_color": "#f5f1e8",
        "department": "전자공학",
        "gap_period": "5개월",
        "certifications": "정보처리기사, 리눅스마스터",
        "employment_field": "백엔드 개발",
        "employment_company_type": "IT서비스",
        "career_path_summary": "전자공학 → 백엔드 개발",
        "similarity_score": 84.0,
        "is_accepted": True,
        "match_note": "전공 기반 개발 직무 전환",
    },
    {
        "user_id": "senior_shin_i",
        "user_name": "신하은",
        "avatar_label": "신하",
        "avatar_color": "#eef0f8",
        "department": "컴퓨터공학",
        "gap_period": "4개월",
        "certifications": "정보처리기사, AWS SAA",
        "employment_field": "클라우드 인프라",
        "employment_company_type": "IT서비스",
        "career_path_summary": "컴퓨터공학 → 클라우드 인프라",
        "similarity_score": 87.0,
        "is_accepted": True,
        "match_note": "자격증과 프로젝트 병행 취업",
    },

    # ── 기획 / 마케팅 계열 ───────────────────────────────────────────
    {
        "user_id": "senior_kang_j",
        "user_name": "강나영",
        "avatar_label": "강나",
        "avatar_color": "#f3f6e8",
        "department": "경영학",
        "gap_period": "5개월",
        "certifications": "ADsP",
        "employment_field": "서비스 기획",
        "employment_company_type": "스타트업",
        "career_path_summary": "경영학 → 스타트업 서비스 기획",
        "similarity_score": 83.0,
        "is_accepted": True,
        "match_note": "경영 지식을 기획 직무로 연결한 사례",
    },
    {
        "user_id": "senior_lim_k",
        "user_name": "임서준",
        "avatar_label": "임서",
        "avatar_color": "#fdf0e8",
        "department": "인문학",
        "gap_period": "9개월",
        "certifications": "SQLD, 컴퓨터활용능력 1급",
        "employment_field": "CRM 마케팅",
        "employment_company_type": "커머스",
        "career_path_summary": "인문학 → CRM 마케팅",
        "similarity_score": 76.0,
        "is_accepted": True,
        "match_note": "데이터 활용 마케팅 직무 전환",
    },
    {
        "user_id": "senior_song_l",
        "user_name": "송민서",
        "avatar_label": "송민",
        "avatar_color": "#f0f4f8",
        "department": "경제학",
        "gap_period": "6개월",
        "certifications": "SQLD, 투자자산운용사",
        "employment_field": "핀테크 데이터 분석",
        "employment_company_type": "핀테크",
        "career_path_summary": "경제학 → 핀테크 데이터 분석",
        "similarity_score": 79.0,
        "is_accepted": True,
        "match_note": "도메인 지식을 데이터 강점으로 전환",
    },

    # ── UI/UX / 디자인 계열 ──────────────────────────────────────────
    {
        "user_id": "senior_jo_m",
        "user_name": "조유진",
        "avatar_label": "조유",
        "avatar_color": "#f9eef5",
        "department": "디자인",
        "gap_period": "6개월",
        "certifications": "GTQ, 웹디자인기능사",
        "employment_field": "UI/UX 디자인",
        "employment_company_type": "에이전시",
        "career_path_summary": "디자인 → UI/UX 에이전시",
        "similarity_score": 80.0,
        "is_accepted": True,
        "match_note": "포트폴리오 개선 중심 합격 사례",
    },
    {
        "user_id": "senior_kwon_n",
        "user_name": "권지민",
        "avatar_label": "권지",
        "avatar_color": "#eef8f0",
        "department": "디자인",
        "gap_period": "4개월",
        "certifications": "GTQ, 컴퓨터활용능력 2급",
        "employment_field": "프로덕트 디자인",
        "employment_company_type": "스타트업",
        "career_path_summary": "디자인 → 스타트업 프로덕트 디자이너",
        "similarity_score": 77.0,
        "is_accepted": True,
        "match_note": "피그마 포트폴리오로 단기 취업",
    },

    # ── 프론트엔드 계열 ──────────────────────────────────────────────
    {
        "user_id": "senior_moon_o",
        "user_name": "문현우",
        "avatar_label": "문현",
        "avatar_color": "#f0f0fa",
        "department": "비전공자",
        "gap_period": "10개월",
        "certifications": "정보처리기사",
        "employment_field": "프론트엔드 개발",
        "employment_company_type": "스타트업",
        "career_path_summary": "비전공 → 프론트엔드 개발",
        "similarity_score": 74.0,
        "is_accepted": True,
        "match_note": "부트캠프 + 자격증 병행으로 전환 성공",
    },
    {
        "user_id": "senior_bae_p",
        "user_name": "배소희",
        "avatar_label": "배소",
        "avatar_color": "#f8f4ed",
        "department": "컴퓨터공학",
        "gap_period": "3개월",
        "certifications": "정보처리기사",
        "employment_field": "프론트엔드 개발",
        "employment_company_type": "IT서비스",
        "career_path_summary": "컴퓨터공학 → 프론트엔드",
        "similarity_score": 86.0,
        "is_accepted": True,
        "match_note": "전공자 단기 취업 사례",
    },

    # ── 임베디드 / 하드웨어 계열 ─────────────────────────────────────
    {
        "user_id": "senior_ahn_q",
        "user_name": "안준혁",
        "avatar_label": "안준",
        "avatar_color": "#eaf5ea",
        "department": "전자공학",
        "gap_period": "8개월",
        "certifications": "정보처리기사, 리눅스마스터",
        "employment_field": "임베디드 개발",
        "employment_company_type": "제조기업",
        "career_path_summary": "전자공학 → 임베디드 개발",
        "similarity_score": 71.0,
        "is_accepted": True,
        "match_note": "전공 프로젝트를 직무 경험으로 전환",
    },

    # ── 회계 / 금융 계열 ─────────────────────────────────────────────
    {
        "user_id": "senior_hong_r",
        "user_name": "홍다은",
        "avatar_label": "홍다",
        "avatar_color": "#fef5e7",
        "department": "경제학",
        "gap_period": "7개월",
        "certifications": "SQLD, 컴퓨터활용능력 1급",
        "employment_field": "데이터 분석",
        "employment_company_type": "금융기업",
        "career_path_summary": "경제학 → 금융권 데이터 분석",
        "similarity_score": 78.0,
        "is_accepted": True,
        "match_note": "경제학 도메인 + 데이터 스킬 결합",
    },
    {
        "user_id": "senior_nam_s",
        "user_name": "남건우",
        "avatar_label": "남건",
        "avatar_color": "#ecf4fb",
        "department": "경영학",
        "gap_period": "11개월",
        "certifications": "컴퓨터활용능력 1급, ADsP",
        "employment_field": "서비스 기획",
        "employment_company_type": "대기업",
        "career_path_summary": "경영학 → 대기업 서비스 기획",
        "similarity_score": 72.0,
        "is_accepted": True,
        "match_note": "장기 공백 극복 사례 - 꾸준한 자격증 취득",
    },
    {
        "user_id": "senior_ryu_t",
        "user_name": "류채원",
        "avatar_label": "류채",
        "avatar_color": "#f0ebe8",
        "department": "인문학",
        "gap_period": "6개월",
        "certifications": "ADsP, 컴퓨터활용능력 1급",
        "employment_field": "데이터 분석",
        "employment_company_type": "중견기업",
        "career_path_summary": "인문학 → 데이터 분석 직무 전환",
        "similarity_score": 75.0,
        "is_accepted": True,
        "match_note": "문과 출신 데이터 전환, ADsP 핵심 자격증",
    },
]


def seed():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        # 기존 데이터 전체 삭제 후 재삽입
        db.query(SeniorPersona).delete()
        db.commit()
        for item in SENIOR_PERSONAS:
            db.add(SeniorPersona(**item))
        db.commit()
        print(f"senior_personas seed complete ({len(SENIOR_PERSONAS)}명)")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
